"use strict";
cc._RF.push(module, '1e0ccPOJnhKW5VBsu9XzriC', 'Z_04_syys_MusicNode');
// Z_04_syys/script/Z_04_syys_MusicNode.js

"use strict";

// Learn cc.Class:
//  - https://docs.cocos.com/creator/manual/en/scripting/class.html
// Learn Attribute:
//  - https://docs.cocos.com/creator/manual/en/scripting/reference/attributes.html
// Learn life-cycle callbacks:
//  - https://docs.cocos.com/creator/manual/en/scripting/life-cycle-callbacks.html
cc.Class({
  "extends": cc.Component,
  properties: {
    // foo: {
    //     // ATTRIBUTES:
    //     default: null,        // The default value will be used only when the component attaching
    //                           // to a node for the first time
    //     type: cc.SpriteFrame, // optional, default is typeof default
    //     serializable: true,   // optional, default is true
    // },
    // bar: {
    //     get () {
    //         return this._bar;
    //     },
    //     set (value) {
    //         this._bar = value;
    //     }
    // },
    开门: {
      "default": null,
      type: cc.AudioClip
    },
    旋转: {
      "default": null,
      type: cc.AudioClip
    },
    植物: {
      "default": null,
      type: cc.AudioClip
    },
    浇水: {
      "default": null,
      type: cc.AudioClip
    },
    走路: {
      "default": null,
      type: cc.AudioClip
    },
    路牌: {
      "default": null,
      type: cc.AudioClip
    },
    门铃: {
      "default": null,
      type: cc.AudioClip
    }
  },
  // LIFE-CYCLE CALLBACKS:
  // onLoad () {},
  start: function start() {},
  playEffect: function playEffect(name, loop, volume) {
    if (loop === void 0) {
      loop = false;
    }

    if (volume === void 0) {
      volume = 1;
    }

    cc.audioEngine.play(this[name], loop, volume);
  } // update (dt) {},

});

cc._RF.pop();